version: '3.8'

services:
  archangel:
    build: ./
    container_name: archangel
    image: archangel:latest
    restart: unless-stopped
    tty: true
    env_file:
      - ./src/.env.development.local
