version: '2.4'

services:
  archangel:
    build: ./
    container_name: archangel
    image: archangel:latest
    restart: unless-stopped
    tty: true
    env_file:
      - ./src/.env.development
      - ./src/.env.production.local
