name: Continuous Delivery

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/continuous-delivery.yml'
  workflow_dispatch:

jobs:
  PublishArchAngel:
    name: Publish ArchAngel image to container registries
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push ArchAngel Docker image
        uses: docker/build-push-action@v3.3.1
        with:
          push: true
          context: ./
          file: Dockerfile
          tags: |
            ghcr.io/favware/archangel:latest
