name: Continuous Delivery

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/continuous-delivery.yml'
  workflow_dispatch:

jobs:
  PublishArchAngel:
    name: Publish ArchAngel image to container registries
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@0d135e0c2fc0dba0729c1a47ecfcf5a3c7f8579e # renovate: tag=v1.3.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c # renovate: tag=v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push ArchAngel Docker image
        uses: docker/build-push-action@e1b7f96249f2e4c8e4ac1519b9608c0d48944a1f # renovate: tag=v2.4.0
        with:
          push: true
          context: ./
          file: Dockerfile
          tags: |
            ghcr.io/favware/archangel:latest
